language: python

python:
  - 2.7

before_install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"

install:
  - "python setup.py install"

script:
  - "make test"

after_success:
    - coveralls